/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.acme.service.Enums;


public enum OPERATE implements org.apache.thrift.TEnum {
  ADD(0),
  SUB(1),
  MUL(2),
  DIV(3);

  private final int value;

  private OPERATE(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static OPERATE findByValue(int value) { 
    switch (value) {
      case 0:
        return ADD;
      case 1:
        return SUB;
      case 2:
        return MUL;
      case 3:
        return DIV;
      default:
        return null;
    }
  }
}
